tabspaces = 8

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
auto_scroll = false
faux_multiplier = 3
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"
title = "@caiangums"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
